### ISSUE TITLE
NPE while opening a JS file which has no Project

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#22]
When I open a JS file in NetBeans, which has no project, it immediately disappears. Until now, I didn't know why, it opens and it closes. Now I got a NPE from ESLint and the while the NPE appears the file closes:

```
java.lang.NullPointerException
	at org.netbeans.modules.projectapi.nb.NbProjectInformationProvider.getProjectInformation(NbProjectInformationProvider.java:75)
	at org.netbeans.api.project.ProjectUtils.getInformation(ProjectUtils.java:96)
	at se.jocke.nb.eslint.ESLint.verify(ESLint.java:100)
	at se.jocke.nb.eslint.annotation.ESLintAnnotationProvider.apply(ESLintAnnotationProvider.java:66)
	at se.jocke.nb.eslint.annotation.ESLintAnnotationProvider.annotate(ESLintAnnotationProvider.java:40)
	at org.openide.text.CloneableEditorSupport.ensureAnnotationsLoaded(CloneableEditorSupport.java:393)
	at org.openide.text.CloneableEditorInitializer.initAnnotations(CloneableEditorInitializer.java:643)
[catch] at org.openide.text.CloneableEditorInitializer.run(CloneableEditorInitializer.java:351)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

```

**Comment by Chris2011** [comment]
Hey, please have a look into the PR and make a new Release 1.1.1. Thx :)

**Comment by Chris2011** [comment]
PR merged, will be released soon.

**Comment by Chris2011** [comment]
Thx for the release @joakim-eriksson would be nice if you can add releases to the github repo too, to see a history what changed in the releases. Thx.
