### ISSUE TITLE
ClassCastException while opening options

### ISSUE THREAD

**Issue by Chris2011** [joakim-eriksson/nb-eslint#25]
I opened the options first, via my shortcut. I went to "Appearance" changed the Muilt-row tabs behaviour, applied and closed the options dialog. I wanted to opened it again and I got this exception, from your plugin, which prevents me from opening the options again:

```
java.lang.ClassCastException: se.jocke.nb.eslint.options.ESLintOptionsPanelController cannot be cast to org.netbeans.spi.options.AdvancedOption
	at org.netbeans.modules.options.TabbedController.readPanels(TabbedController.java:311)
	at org.netbeans.modules.options.TabbedController.<init>(TabbedController.java:97)
	at org.netbeans.modules.options.OptionsCategoryImpl.create(OptionsCategoryImpl.java:94)
	at org.netbeans.modules.options.CategoryModel$Category.create(CategoryModel.java:360)
	at org.netbeans.modules.options.CategoryModel$Category.getComponent(CategoryModel.java:409)
	at org.netbeans.modules.options.CategoryModel$Category.update(CategoryModel.java:368)
	at org.netbeans.modules.options.CategoryModel.update(CategoryModel.java:190)
	at org.netbeans.modules.options.OptionsPanel.update(OptionsPanel.java:269)
	at org.netbeans.modules.options.OptionsDisplayerImpl.showOptionsDialog(OptionsDisplayerImpl.java:203)
	at org.netbeans.api.options.OptionsDisplayer$3.run(OptionsDisplayer.java:223)
	at org.netbeans.api.options.OptionsDisplayer$3.run(OptionsDisplayer.java:209)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:115)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:75)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:193)
	at org.netbeans.api.options.OptionsDisplayer.openImpl(OptionsDisplayer.java:209)
	at org.netbeans.api.options.OptionsDisplayer.open(OptionsDisplayer.java:156)
	at org.netbeans.api.options.OptionsDisplayer.open(OptionsDisplayer.java:109)
	at org.netbeans.api.options.OptionsDisplayer.open(OptionsDisplayer.java:172)
	at org.netbeans.modules.options.OptionsWindowAction.actionPerformed(OptionsWindowAction.java:39)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:174)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:177)
	at org.openide.windows.TopComponent.processKeyBinding(TopComponent.java:1151)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6366)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:871)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1140)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1010)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:836)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4847)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by Chris2011** [comment]
Unfortunately or luckily, I can't reproduce it anymore. So we can close the ticket and I will create a new one, when I have more information.
